# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('diminutif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreVf', models.CharField(max_length=500)),
                ('titreVo', models.CharField(max_length=500)),
                ('codeAyantDroit', models.CharField(max_length=100)),
                ('vodStart', models.DateField()),
                ('vodEnd', models.DateField()),
                ('svodStart', models.DateField()),
                ('svodEnd', models.DateField()),
                ('realisateur', models.TextField()),
                ('casting', models.TextField()),
                ('paysProduction', models.TextField()),
                ('anneeProduction', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('dateSortieVideo', models.DateField()),
                ('imdb', models.URLField(max_length=500)),
                ('visuel', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydc.Contenu')),
                ('dateSortieSalle', models.DateField()),
                ('duree', models.DurationField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydc.Categorie')),
            ],
            bases=('mydc.contenu',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mydc.Contenu')),
                ('format', models.DurationField()),
            ],
            bases=('mydc.contenu',),
        ),
        migrations.AddField(
            model_name='contenu',
            name='ayantDroit',
            field=models.ManyToManyField(to='mydc.AyantDroit'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='droits',
            field=models.ManyToManyField(to='mydc.Droit'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='mydc.Genre'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='mydc.Rating'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='sousGenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousgenre', to='mydc.Genre'),
        ),
    ]
