# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='anneeProduction',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='casting',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='codeAyantDroit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='dateSortieVideo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='droits',
            field=models.ManyToManyField(blank=True, to='mydc.Droit'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='mydc.Genre'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='imdb',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='paysProduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='mydc.Rating'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='realisateur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='sousGenre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sousgenre', to='mydc.Genre'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='svodEnd',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='svodStart',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='visuel',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='vodEnd',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='vodStart',
            field=models.DateField(blank=True),
        ),
    ]
