# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0002_auto_20161019_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='mydc.Genre'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='mydc.Rating'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='sousGenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousgenre', to='mydc.Genre'),
        ),
    ]
