# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0003_auto_20161019_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayantdroit',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='dateSortieSalle',
            field=models.DateField(blank=True),
        ),
    ]
