# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0004_auto_20161019_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='visuel',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.DurationField(blank=True),
        ),
    ]
