# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0006_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='visuel',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
