# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0007_catalogue_visuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='visuel',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
