# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydc', '0008_auto_20161104_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duree',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
